spring.application.name=sistema-pescd
spring.datasource.url=jdbc:h2:mem:pescd;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
# Habilita o Hibernate para criar o schema ANTES do script SQL rodar
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.messages.basename=messages
# Aumenta o log para ver exatamente o que acontece no banco e seguranca
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Configuracoes de upload
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.resolve-lazily=true
upload.path=src/main/resources/static/uploads
