spring.application.name=sistema-pescd
spring.datasource.url=jdbc:mysql://localhost:3306/pescd_db?createDatabaseIfNotExist=true&serverTimezone=UTC
# spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=pescd_user
spring.datasource.password=senha123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Habilita o Hibernate para criar o schema ANTES do script SQL rodar
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.messages.basename=messages
# Aumenta o log para ver exatamente o que acontece no banco e seguranca
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
upload.path=uploads
